testing if to catch exit code

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -53,7 +53,13 @@ steps:
   entrypoint: "bash"
   args:
     - "-c"
-    - ../gke-deploy run --filename=resource.yml --location=us-west1-a --cluster="gke-e2e-demo" || echo "fail" > /workspace/deployment-status.txt
+    - ../gke-deploy run --filename=resource1111.yml --location=us-west1-a --cluster="gke-e2e-demo"
+    - |
+      if [ $? -eq 0 ] then
+        echo "Success: deployment was successfully" > /workspace/deployment-status.txt
+      else
+        echo "fail" > /workspace/deployment-status.txt
+      fi
   waitFor: ['whitelist']
 
 ## Delete the node IP from the control plane endpoint whitelist
@@ -69,7 +75,7 @@ steps:
     - '-c'
     - |
       if [[ $(< /workspace/deployment-status.txt) == "fail" ]]; then
-        echo "deployment step failed, please review"
+        echo "deployment step failed, please check that step for further details"
         exit 1
       else
         echo "the deployment step was successfully"
