testing deployment catch

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -51,12 +51,7 @@ steps:
   entrypoint: "bash"
   args:
     - "-c"
-    - |
-        echo "show content of builder image"
-        pwd
-        cd /
-        ls -la
-        gke-deploy run --filename=resource.yml --location=us-west1-a --cluster="gke-e2e-demo" || echo "fail" > /workspace/deployment-status.txt
+    - ../gke-deploy run --filename=resource.yml --location=us-west1-a --cluster="gke-e2e-demo" || echo "fail" > /workspace/deployment-status.txt
   # args:
   # - run
   # -
@@ -75,5 +70,6 @@ steps:
     - '-c'
     - |
       if [[ $(< /workspace/deployment-status.txt) == "fail" ]]; then
+        echo "deployment step failed, please review"
         exit 1
       fi
